source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'AKAttributeKit_Example' do
  pod "AKAttributeKit", :path => "../"
end

target 'AKAttributeKit_Tests' do
  pod "AKAttributeKit", :path => "../"

  
end
